name = "short-url-redirect"
main = "short-url/src/index.ts"
compatibility_date = "2025-12-13"

kv_namespaces = [
  { binding = "SHORT_URLS_REDIRECT", id = "607a0dadd70149759a841ff80925e80e" }
]

[vars]
API_URL = "https://secure-short-url-genrator.onrender.com"
